# Conform to: https://wiki.parity.io/Substrate-Style-Guide
reorder_imports = true
hard_tabs = true
max_width = 120

# Temp workaround for https://github.com/paritytech/substrate/issues/2114
# REMOVE THIS RULE WHEN FIXED
ignore = [
	"crml/fees/src/lib.rs"
]
