[package]
name = "cennznet-runtime"
version = "0.1.0"
authors = ["Centrality Developers <developers@centrality.ai>"]

[dependencies]
rustc-hex = "1.0"
hex-literal = "0.1.0"
serde = { version = "1.0", default-features = false }
serde_derive = { version = "1.0", optional = true }
safe-mix = { version = "1.0", default-features = false }
parity-codec = "2.0"
parity-codec-derive = "2.0"
sr-std = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
sr-io = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-support = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
substrate-primitives = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
substrate-keyring = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-balances = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-consensus = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-contract = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-council = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-democracy = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-executive = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
sr-primitives = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-session = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-staking = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-system = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-timestamp = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-treasury = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
srml-upgrade-key = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
substrate-client = { git = "https://github.com/cennznet/substrate", branch = 'cennznet', optional = true }
sr-version = { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
substrate-finality-grandpa-primitives =  { git = "https://github.com/cennznet/substrate", branch = 'cennznet' }
cennznet-primitives = { path = "../primitives" }

[features]
default = ["std"]
std = [
	"parity-codec/std",
	"substrate-primitives/std",
	"sr-std/std",
	"srml-support/std",
	"srml-balances/std",
	"srml-consensus/std",
	"srml-contract/std",
	"srml-council/std",
	"srml-democracy/std",
	"srml-executive/std",
	"sr-primitives/std",
	"srml-session/std",
	"srml-staking/std",
	"srml-system/std",
	"srml-timestamp/std",
	"srml-treasury/std",
	"srml-upgrade-key/std",
	"sr-version/std",
	"cennznet-primitives/std",
	"serde_derive",
	"serde/std",
	"safe-mix/std",
	"substrate-client/std",
	"substrate-finality-grandpa-primitives/std",
]
