# Default values for cennznet-bootnodes
cennznet-bootnode:
  namespace: "cennznet-bootnodes"
  appName: "cennznet-bootnodes"

  image:
    repository: centralitycontainerregistry-on.azurecr.io/centrality
    name: cennznet
  genesisBlock:
    create: false
    secretName: genesis-block

  bootnodes:
    - keySecrets:
        enable: true
        secretName: bootnode-0
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "BOOTNODE_0"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-bootnode-1.centrality.me/tcp/30333/p2p/QmRaZu8UNGejxuGB9pMhjw5GZEVVBkaRiYYhhLYYUkT8qa
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-bootnode-2.centrality.me/tcp/30333/p2p/QmTEUaAyqq3spjKSFLWw5gG8tzZ6xwbt5ptTKvs65VkBPJ
        - name: CENNZNET_BOOTNODE_3
          value: /dns4/cennznet-bootnode-3.centrality.me/tcp/30333/p2p/Qme2G1fQaUtLH1TTRTNqbBDUGcgSr8od397Q6hcrLavodd
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      annotations:
        external:
          external-dns.alpha.kubernetes.io/hostname: cennznet-bootnode-0.centrality.me
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    - keySecrets:
        enable: true
        secretName: bootnode-1
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "BOOTNODE_1"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-bootnode-0.centrality.me/tcp/30333/p2p/Qmdpvn9xttHZ5SQePVhhsk8dFMHCUaS3EDQcGDZ8MuKbx2
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-bootnode-2.centrality.me/tcp/30333/p2p/QmTEUaAyqq3spjKSFLWw5gG8tzZ6xwbt5ptTKvs65VkBPJ
        - name: CENNZNET_BOOTNODE_3
          value: /dns4/cennznet-bootnode-3.centrality.me/tcp/30333/p2p/Qme2G1fQaUtLH1TTRTNqbBDUGcgSr8od397Q6hcrLavodd
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      annotations:
        external:
          external-dns.alpha.kubernetes.io/hostname: cennznet-bootnode-1.centrality.me
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    - keySecrets:
        enable: true
        secretName: bootnode-2
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "BOOTNODE_2"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-bootnode-0.centrality.me/tcp/30333/p2p/Qmdpvn9xttHZ5SQePVhhsk8dFMHCUaS3EDQcGDZ8MuKbx2
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-bootnode-1.centrality.me/tcp/30333/p2p/QmRaZu8UNGejxuGB9pMhjw5GZEVVBkaRiYYhhLYYUkT8qa
        - name: CENNZNET_BOOTNODE_3
          value: /dns4/cennznet-bootnode-3.centrality.me/tcp/30333/p2p/Qme2G1fQaUtLH1TTRTNqbBDUGcgSr8od397Q6hcrLavodd
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      annotations:
        external:
          external-dns.alpha.kubernetes.io/hostname: cennznet-bootnode-2.centrality.me
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    - keySecrets:
        enable: true
        secretName: bootnode-3
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "BOOTNODE_3"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-bootnode-0.centrality.me/tcp/30333/p2p/Qmdpvn9xttHZ5SQePVhhsk8dFMHCUaS3EDQcGDZ8MuKbx2
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-bootnode-1.centrality.me/tcp/30333/p2p/QmRaZu8UNGejxuGB9pMhjw5GZEVVBkaRiYYhhLYYUkT8qa
        - name: CENNZNET_BOOTNODE_3
          value: /dns4/cennznet-bootnode-2.centrality.me/tcp/30333/p2p/QmTEUaAyqq3spjKSFLWw5gG8tzZ6xwbt5ptTKvs65VkBPJ
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      annotations:
        external:
          external-dns.alpha.kubernetes.io/hostname: cennznet-bootnode-3.centrality.me
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"


  command:
    - "/bin/bash"
    - "-c"
    - >
      cennznet
      --chain=kauri
      --pruning=archive
      --key=$CENNZNET_KEY
      --name=$CENNZNET_NAME
      --node-key=$CENNZNET_NODE_KEY
      --bootnodes=$CENNZNET_BOOTNODE_1
      --bootnodes=$CENNZNET_BOOTNODE_2
      --bootnodes=$CENNZNET_BOOTNODE_3
      --telemetry-url=$CENNZNET_TELEMETRY_URL

  resources:
    memory: "256Mi"
    cpu: "500m"

  services:
    external:
      createService: true
      createLoadBalancer: true
      ports:
        - port: 30333
          name: p2p
    internal:
      createService: true
      ports:
        - port: 30333
          name: p2p
    main:
      ports:
        - port: 30333
          name: p2p

  storageSize: 20Gi

  whitelistIPs:
  - 203.118.138.130/32 # AKL office IP
  - 13.73.107.121/32 # AKL office backup
  - 118.127.126.86/32 # MEL office
  - 52.220.204.131/32 # k8s-dev NAT gateway
  - 13.228.46.235/32 # k8s-uat NAT gateway
  - 18.136.19.89/32 # cennzscan
  - 222.154.246.210/32 # singlesource
  - 13.251.201.221/32 # terraform vpc 1a NAT gateway - eks-dev
  - 13.251.201.8/32 # terraform vpc 1c NAT gateway - eks-dev
  - 13.251.209.118/32 # terraform vpc 1b NAT gateway - eks-dev
  - 222.154.239.179/32 # sylo