cennznet-node:
  nodes:
    - env:
        - name: RUST_LOG
          value: "debug"
        - name: CENNZNET_KEY
          value: "Andrea"
        - name: CENNZNET_NAME
          value: ANDREA
        - name: CENNZNET_NODE_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000011"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-node-1.centrality.me/tcp/30333/p2p/QmRaZu8UNGejxuGB9pMhjw5GZEVVBkaRiYYhhLYYUkT8qa
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-node-2.centrality.me/tcp/30333/p2p/QmTEUaAyqq3spjKSFLWw5gG8tzZ6xwbt5ptTKvs65VkBPJ
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      domainName: cennznet-node-0.centrality.me
    - env:
        - name: CENNZNET_KEY
          value: "Brooke"
        - name: CENNZNET_NAME
          value: BROOKE
        - name: CENNZNET_NODE_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000012"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-node-0.centrality.me/tcp/30333/p2p/Qmdpvn9xttHZ5SQePVhhsk8dFMHCUaS3EDQcGDZ8MuKbx2
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-node-2.centrality.me/tcp/30333/p2p/QmTEUaAyqq3spjKSFLWw5gG8tzZ6xwbt5ptTKvs65VkBPJ
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      domainName: cennznet-node-1.centrality.me
    - env:
        - name: CENNZNET_KEY
          value: "Courtney"
        - name: CENNZNET_NAME
          value: COURTNEY
        - name: CENNZNET_NODE_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000013"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-node-0.centrality.me/tcp/30333/p2p/Qmdpvn9xttHZ5SQePVhhsk8dFMHCUaS3EDQcGDZ8MuKbx2
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-node-1.centrality.me/tcp/30333/p2p/QmRaZu8UNGejxuGB9pMhjw5GZEVVBkaRiYYhhLYYUkT8qa
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      domainName: cennznet-node-2.centrality.me

  command:
    - "/bin/bash"
    - "-c"
    - >
      cennznet
      --chain=cennznet-dev
      --base-path=/mnt/cennznet
      --validator
      --pruning=archive
      --rpc-external
      --ws-external
      --key=$CENNZNET_KEY
      --name=$CENNZNET_NAME
      --node-key=$CENNZNET_NODE_KEY
      --bootnodes=$CENNZNET_BOOTNODE_1
      --bootnodes=$CENNZNET_BOOTNODE_2
      --telemetry-url=$CENNZNET_TELEMETRY_URL

  whitelistIPs:
  - 203.118.138.130/32 # AKL office IP
  - 13.73.107.121/32 # AKL office backup
  - 118.127.126.86/32 # MEL office
  - 13.73.101.35/32 # jenkins slave 1
  - 13.73.101.111/32 # jenkins slave 2
  - 52.220.204.131/32 # k8s-dev NAT gateway
  - 13.228.46.235/32 # k8s-uat NAT gateway
  - 18.136.19.89/32 # cennzscan
  - 13.77.41.0/32  # windows jenkins agent
  - 222.154.246.210/32 # singlesource
