cennznet-node:
  nodes:
    - env:
        - name: RUST_LOG
          value: "sync,afg=trace"
        - name: CENNZNET_KEY
          value: "Andrea"
        - name: CENNZNET_NAME
          value: ANDREA
        - name: CENNZNET_NODE_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000001"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-bootnode-1.centrality.cloud/tcp/30333/p2p/QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-bootnode-2.centrality.cloud/tcp/30333/p2p/QmYcHeEWuqtr6Gb5EbK7zEhnaCm5p6vA2kWcVjFKbhApaC
        - name: CENNZNET_BOOTNODE_3
          value: /dns4/cennznet-bootnode-3.centrality.cloud/tcp/30333/p2p/QmZq8Hqo53vAMUeQpoHsVichpcsvdoNmBSojM6qSdurd4Y
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      annotations:
        rpc:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:921717751722:certificate/ebeccca7-7425-4bbc-a72a-9b62160fbfd1
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9933,9944"
          external-dns.alpha.kubernetes.io/hostname: cennznet-node-0.centrality.cloud
        p2p:
          external-dns.alpha.kubernetes.io/hostname: cennznet-bootnode-0.centrality.cloud
    - env:
        - name: CENNZNET_KEY
          value: "Brooke"
        - name: CENNZNET_NAME
          value: BROOKE
        - name: CENNZNET_NODE_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000002"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-bootnode-0.centrality.cloud/tcp/30333/p2p/QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-bootnode-2.centrality.cloud/tcp/30333/p2p/QmYcHeEWuqtr6Gb5EbK7zEhnaCm5p6vA2kWcVjFKbhApaC
        - name: CENNZNET_BOOTNODE_3
          value: /dns4/cennznet-bootnode-3.centrality.cloud/tcp/30333/p2p/QmZq8Hqo53vAMUeQpoHsVichpcsvdoNmBSojM6qSdurd4Y
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      annotations:
        rpc:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:921717751722:certificate/ebeccca7-7425-4bbc-a72a-9b62160fbfd1
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9933,9944"
          external-dns.alpha.kubernetes.io/hostname: cennznet-node-1.centrality.cloud
        p2p:
          external-dns.alpha.kubernetes.io/hostname: cennznet-bootnode-1.centrality.cloud
    - env:
        - name: CENNZNET_KEY
          value: "Courtney"
        - name: CENNZNET_NAME
          value: COURTNEY
        - name: CENNZNET_NODE_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000003"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-bootnode-0.centrality.cloud/tcp/30333/p2p/QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-bootnode-1.centrality.cloud/tcp/30333/p2p/QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK
        - name: CENNZNET_BOOTNODE_3
          value: /dns4/cennznet-bootnode-3.centrality.cloud/tcp/30333/p2p/QmZq8Hqo53vAMUeQpoHsVichpcsvdoNmBSojM6qSdurd4Y
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      annotations:
        rpc:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:921717751722:certificate/ebeccca7-7425-4bbc-a72a-9b62160fbfd1
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9933,9944"
          external-dns.alpha.kubernetes.io/hostname: cennznet-node-2.centrality.cloud
        p2p:
          external-dns.alpha.kubernetes.io/hostname: cennznet-bootnode-2.centrality.cloud
    - env:
        - name: CENNZNET_KEY
          value: "Drew"
        - name: CENNZNET_NAME
          value: DREW
        - name: CENNZNET_NODE_KEY
          value: "0000000000000000000000000000000000000000000000000000000000000004"
        - name: CENNZNET_BOOTNODE_1
          value: /dns4/cennznet-bootnode-0.centrality.cloud/tcp/30333/p2p/QmQZ8TjTqeDj3ciwr93EJ95hxfDsb9pEYDizUAbWpigtQN
        - name: CENNZNET_BOOTNODE_2
          value: /dns4/cennznet-bootnode-1.centrality.cloud/tcp/30333/p2p/QmXiB3jqqn2rpiKU7k1h7NJYeBg8WNSx9DiTRKz9ti2KSK
        - name: CENNZNET_BOOTNODE_3
          value: /dns4/cennznet-bootnode-2.centrality.cloud/tcp/30333/p2p/QmYcHeEWuqtr6Gb5EbK7zEhnaCm5p6vA2kWcVjFKbhApaC
        - name: CENNZNET_TELEMETRY_URL
          value: ws://cennznet-telemetry.centrality.me:1024
      annotations:
        rpc:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:921717751722:certificate/ebeccca7-7425-4bbc-a72a-9b62160fbfd1
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9933,9944"
          external-dns.alpha.kubernetes.io/hostname: cennznet-node-3.centrality.cloud
        p2p:
          external-dns.alpha.kubernetes.io/hostname: cennznet-bootnode-3.centrality.cloud

  command:
    - "/bin/bash"
    - "-c"
    - >
      cennznet
      --chain=rimu
      --base-path=/mnt/cennznet
      --validator
      --rpc-external
      --ws-external
      --pruning=archive
      --key=$CENNZNET_KEY
      --name=$CENNZNET_NAME
      --node-key=$CENNZNET_NODE_KEY
      --bootnodes=$CENNZNET_BOOTNODE_1
      --bootnodes=$CENNZNET_BOOTNODE_2
      --bootnodes=$CENNZNET_BOOTNODE_3
      --telemetry-url=$CENNZNET_TELEMETRY_URL

  tolerations:
    - effect: NoSchedule
      operator: Exists

  resources:
    memory: "14Gi"
    cpu: "3.5"

  whitelistIPs:
  - 203.118.138.130/32 # AKL office IP
  - 13.73.107.121/32 # AKL office backup
  - 118.127.126.86/32 # MEL office
  - 13.73.101.35/32 # jenkins slave 1
  - 13.73.101.111/32 # jenkins slave 2
  - 52.220.204.131/32 # k8s-dev NAT gateway
  - 13.228.46.235/32 # k8s-uat NAT gateway
  - 18.136.19.89/32 # cennzscan
  - 13.77.41.0/32 # windows jenkins agent
  - 222.154.246.210/32 # singlesource
  - 13.251.201.221/32 # terraform vpc 1a NAT gateway - eks-dev
  - 13.251.201.8/32 # terraform vpc 1c NAT gateway - eks-dev
  - 13.251.209.118/32 # terraform vpc 1b NAT gateway - eks-dev
  - 222.154.239.179/32 # sylo
