
cennznet-validator:
  namespace: "cennznet"
  appName: "cennznet-validators"

  image:
    repository: centralitycontainerregistry-on.azurecr.io/centrality
    name: cennznet
  genesisBlock:
    create: false
    secretName: genesis-block

  monitor:
    create: true
    image:
      repository: centralitycontainerregistry-on.azurecr.io/centrality
      name: run-monitor
      tag: latest

  fullnodes:
    - keySecrets:
        enable: true
        secretName: fullnode-0
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "FULLNODE_0"
        - name: CENNZNET_BOOTNODE_1
          value: "/dns4/cennznet-bootnodes-0-p2p-internal.cennznet-bootnodes/tcp/30333/p2p/Qmdpvn9xttHZ5SQePVhhsk8dFMHCUaS3EDQcGDZ8MuKbx2"
        - name: CENNZNET_RESERVEDNODE_1
          value: "/dns4/cennznet-bootnodes-0-p2p-internal.cennznet-bootnodes/tcp/30333/p2p/Qmdpvn9xttHZ5SQePVhhsk8dFMHCUaS3EDQcGDZ8MuKbx2"
        - name: CENNZNET_RESERVEDNODE_2
          value: "/dns4/cennznet-validator-validator-0-p2p-internal.cennznet/tcp/30333/p2p/QmeD5r1qpFAsZMcDQoBt93TE7jekdz4qkyYQXScLiqWNCG"
        - name: CENNZNET_TELEMETRY_URL
          value: "ws://cennznet-telemetry.centrality.me:1024"
      annotations:
        external:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:225301848476:certificate/377bc2cc-a42a-4e9d-b839-8b97fdaed3c7
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9933,9944"
          external-dns.alpha.kubernetes.io/hostname: cennznet-node-0.centrality.me
    - keySecrets:
        enable: true
        secretName: fullnode-1
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "FULLNODE_1"
        - name: CENNZNET_BOOTNODE_1
          value: "/dns4/cennznet-bootnodes-1-p2p-internal.cennznet-bootnodes/tcp/30333/p2p/QmRaZu8UNGejxuGB9pMhjw5GZEVVBkaRiYYhhLYYUkT8qa"
        - name: CENNZNET_RESERVEDNODE_1
          value: "/dns4/cennznet-bootnodes-1-p2p-internal.cennznet-bootnodes/tcp/30333/p2p/QmRaZu8UNGejxuGB9pMhjw5GZEVVBkaRiYYhhLYYUkT8qa"
        - name: CENNZNET_RESERVEDNODE_2
          value: "/dns4/cennznet-validator-validator-1-p2p-internal.cennznet/tcp/30333/p2p/QmZM1etuBn8rysv2qqduwWJc2FLqVApmnoRc3PDQqLe5C8"
        - name: CENNZNET_TELEMETRY_URL
          value: "ws://cennznet-telemetry.centrality.me:1024"
      annotations:
        external:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:225301848476:certificate/377bc2cc-a42a-4e9d-b839-8b97fdaed3c7
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9933,9944"
          external-dns.alpha.kubernetes.io/hostname: cennznet-node-1.centrality.me
    - keySecrets:
        enable: true
        secretName: fullnode-2
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "FULLNODE_2"
        - name: CENNZNET_BOOTNODE_1
          value: "/dns4/cennznet-bootnodes-2-p2p-internal.cennznet-bootnodes/tcp/30333/p2p/QmTEUaAyqq3spjKSFLWw5gG8tzZ6xwbt5ptTKvs65VkBPJ"
        - name: CENNZNET_RESERVEDNODE_1
          value: "/dns4/cennznet-bootnodes-2-p2p-internal.cennznet-bootnodes/tcp/30333/p2p/QmTEUaAyqq3spjKSFLWw5gG8tzZ6xwbt5ptTKvs65VkBPJ"
        - name: CENNZNET_RESERVEDNODE_2
          value: "/dns4/cennznet-validator-validator-2-p2p-internal.cennznet/tcp/30333/p2p/QmSSs59jRQuiN1xDK7nU2eUbxCZsWjHKHcYsjPp2jtPYDW"
        - name: CENNZNET_TELEMETRY_URL
          value: "ws://cennznet-telemetry.centrality.me:1024"
      annotations:
        external:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:225301848476:certificate/377bc2cc-a42a-4e9d-b839-8b97fdaed3c7
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9933,9944"
          external-dns.alpha.kubernetes.io/hostname: cennznet-node-2.centrality.me
    - keySecrets:
        enable: true
        secretName: fullnode-3
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "FULLNODE_3"
        - name: CENNZNET_BOOTNODE_1
          value: "/dns4/cennznet-bootnodes-3-p2p-internal.cennznet-bootnodes/tcp/30333/p2p/Qme2G1fQaUtLH1TTRTNqbBDUGcgSr8od397Q6hcrLavodd"
        - name: CENNZNET_RESERVEDNODE_1
          value: "/dns4/cennznet-bootnodes-3-p2p-internal.cennznet-bootnodes/tcp/30333/p2p/Qme2G1fQaUtLH1TTRTNqbBDUGcgSr8od397Q6hcrLavodd"
        - name: CENNZNET_RESERVEDNODE_2
          value: "/dns4/cennznet-validator-validator-3-p2p-internal.cennznet/tcp/30333/p2p/QmUibwR4jTbbBcGxDo8P9CFziGvnMpTTswT4Uo2kUgBGoJ"
        - name: CENNZNET_TELEMETRY_URL
          value: "ws://cennznet-telemetry.centrality.me:1024"
      annotations:
        external:
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:225301848476:certificate/377bc2cc-a42a-4e9d-b839-8b97fdaed3c7
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9933,9944"
          external-dns.alpha.kubernetes.io/hostname: cennznet-node-3.centrality.me

  validatornodes:
    - keySecrets:
        enable: true
        secretName: validator-0
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "VALIDATOR_0"
        - name: CENNZNET_BOOTNODE_1
          value: "/dns4/cennznet-validator-full-0-p2p-internal.cennznet/tcp/30333/p2p/QmVMfxFqB9iHTDRWqtzms5hd1pSGk5h9TVBMYYsDHqLkYe"
        - name: CENNZNET_RESERVEDNODE_1
          value: "/dns4/ccennznet-validator-full-0-p2p-internal.cennznet/tcp/30333/p2p/QmVMfxFqB9iHTDRWqtzms5hd1pSGk5h9TVBMYYsDHqLkYe"
        - name: CENNZNET_TELEMETRY_URL
          value: "ws://cennznet-telemetry.centrality.me:1024"
    - keySecrets:
        enable: true
        secretName: validator-1
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "VALIDATOR_1"
        - name: CENNZNET_BOOTNODE_1
          value: "/dns4/cennznet-validator-full-1-p2p-internal.cennznet/tcp/30333/p2p/QmY1C59EZKS6G7witH6xiRNs2YfEnJTUuzdFemwqWo4HL8"
        - name: CENNZNET_RESERVEDNODE_1
          value: "/dns4/cennznet-validator-full-1-p2p-internal.cennznet/tcp/30333/p2p/QmY1C59EZKS6G7witH6xiRNs2YfEnJTUuzdFemwqWo4HL8"
        - name: CENNZNET_TELEMETRY_URL
          value: "ws://cennznet-telemetry.centrality.me:1024"
    - keySecrets:
        enable: true
        secretName: validator-2
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "VALIDATOR_2"
        - name: CENNZNET_BOOTNODE_1
          value: "/dns4/cennznet-validator-full-2-p2p-internal.cennznet/tcp/30333/p2p/QmcxyvK7ncc7VPmrKRcjcpwheNsjkMRrjfjrneKcbyAYCG"
        - name: CENNZNET_RESERVEDNODE_1
          value: "/dns4/cennznet-validator-full-2-p2p-internal.cennznet/tcp/30333/p2p/QmcxyvK7ncc7VPmrKRcjcpwheNsjkMRrjfjrneKcbyAYCG"
        - name: CENNZNET_TELEMETRY_URL
          value: "ws://cennznet-telemetry.centrality.me:1024"
    - keySecrets:
        enable: true
        secretName: validator-3
        keyName: key
        nodeKeyName: nodeKey
      env:
        - name: CENNZNET_NAME
          value: "VALIDATOR_3"
        - name: CENNZNET_BOOTNODE_1
          value: "/dns4/cennznet-validator-full-3-p2p-internal.cennznet/tcp/30333/p2p/QmeJMPTAxiMVezKvituWCT1cGM1wc4itREvTWzeQmWFgH1"
        - name: CENNZNET_RESERVEDNODE_1
          value: "/dns4/cennznet-validator-full-3-p2p-internal.cennznet/tcp/30333/p2p/QmeJMPTAxiMVezKvituWCT1cGM1wc4itREvTWzeQmWFgH1"
        - name: CENNZNET_TELEMETRY_URL
          value: "ws://cennznet-telemetry.centrality.me:1024"


  validatorCommand:
    - "/bin/bash"
    - "-c"
    - >
      cennznet
      --chain=kauri
      --base-path=/mnt/cennznet
      --pruning=archive
      --validator
      --key=$CENNZNET_KEY
      --name=$CENNZNET_NAME
      --node-key=$CENNZNET_NODE_KEY
      --node-key-type=secp256k1
      --telemetry-url=$CENNZNET_TELEMETRY_URL
      --bootnodes=$CENNZNET_BOOTNODE_1
      --bootnodes=$CENNZNET_RESERVEDNODE_1
      -lafg

  fullnodeCommand:
    - "/bin/bash"
    - "-c"
    - >
      cennznet
      --chain=kauri
      --base-path=/mnt/cennznet
      --pruning=archive
      --rpc-external
      --ws-external
      --key=$CENNZNET_KEY
      --name=$CENNZNET_NAME
      --node-key=$CENNZNET_NODE_KEY
      --node-key-type=secp256k1
      --telemetry-url=$CENNZNET_TELEMETRY_URL
      --bootnodes=$CENNZNET_BOOTNODE_1
      --bootnodes=$CENNZNET_RESERVEDNODE_2
      -lafg

  resources:
    memory: "384Mi"
    cpu: "800m"

  fullnodeServices:
    external:
      createService: true
      createLoadBalancer: true
      ports:
        - port: 9933
          name: rpc-http
        - port: 9944
          name: rpc-ws
    internal:
      createService: true
      ports:
        - port: 30333
          name: p2p
    main:
      ports:
        - port: 9933
          name: rpc-http
        - port: 9944
          name: rpc-ws

  validatorServices:
    internal:
      createService: true
      ports:
        - port: 30333
          name: p2p

  storageSize: 20Gi

  whitelistIPs:
  - 203.118.138.130/32 # AKL office IP
  - 13.73.107.121/32 # AKL office backup
  - 52.220.204.131/32 # k8s-dev NAT gateway
  - 13.228.46.235/32 # k8s-uat NAT gateway
  - 18.136.19.89/32 # cennzscan
  - 222.154.246.210/32 # singlesource
  - 13.251.201.221/32 # terraform vpc 1a NAT gateway - eks-dev
  - 13.251.201.8/32 # terraform vpc 1c NAT gateway - eks-dev
  - 13.251.209.118/32 # terraform vpc 1b NAT gateway - eks-dev
  - 222.154.239.179/32 # sylo
